# This is a basic workflow to help you get started with Actions

name: Build Apk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Flutter
      # You may pin to the exact commit or the version.
      # uses: britannio/action-install-flutter@a486b7e3148e54a76390d849100b9dee819ff810
        uses: britannio/action-install-flutter@v1.1

      # Runs a set of commands using the runners shell
      - name: build release
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build apk --release --flavor development
          
      - name: Upload Diawi
        # You may pin to the exact commit or the version.
        # uses: rnkdsh/action-upload-diawi@71cc0f6afd5ed99ecaf97426ccb2790a20175f4b
        uses: rnkdsh/action-upload-diawi@v1.2.1
        with:
          # Diawi API access token
          token: tBsjh0BumgsYduuI3s5BpFMhWaMPRhReea34fcOl2q
          # APK file to upload on Diawi
          file: build/app/outputs/flutter-apk/app-development-release.apk