

name: Build and release Apk

on:
  push:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
      - name: build prod
        run: |
          flutter pub get
          flutter test
          flutter build apk --release --flavor prod
#      - name: release prod
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/app-prod-release.apk"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.DeployApp }}

          