name: Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install FLutter
        uses: britannio/action-install-flutter@v1.1
        # with:
        #   version: 2.8.1

      - name: run pipline and build apk
        run: |
          flutter clean
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter format --set-exit-if-changed .
          flutter build apk --release --flavor development

      - name: Upload Diawi
        # You may pin to the exact commit or the version.
        # uses: rnkdsh/action-upload-diawi@71cc0f6afd5ed99ecaf97426ccb2790a20175f4b
        uses: rnkdsh/action-upload-diawi@v1.2.1
        with:
          # Diawi API access token
          token: tBsjh0BumgsYduuI3s5BpFMhWaMPRhReea34fcOl2q
          # APK file to upload on Diawi
          file: build/app/outputs/flutter-apk/app-development-release.apk